Document: ergo
Title: Debian ergo Manual
Author: <insert document author here>
Abstract: This manual describes what ergo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ergo/ergo.sgml.gz

Format: postscript
Files: /usr/share/doc/ergo/ergo.ps.gz

Format: text
Files: /usr/share/doc/ergo/ergo.text.gz

Format: HTML
Index: /usr/share/doc/ergo/html/index.html
Files: /usr/share/doc/ergo/html/*.html
